#
# Copyright (C) 2014 EZchip, Inc. (www.ezchip.com)
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#

obj-y += nps.o
obj-y += ddr.o 
obj-y += common.o
